### PR TITLE
changed structure for ease

### PR DESCRIPTION
**Pull request by kamalkoranga**

### CODE REVIEW

**Comment by kamalkoranga** [comment]
Hello, I think this structure will be great...

**Comment by mahmoudessam820** [comment]
Hi, @Kamalkoranga 

My sincere appreciation goes out to you for your contribution and your efforts. 

I will review your new structure and come back to you to talk about it.

**Comment by kamalkoranga** [comment]
> Hi, @Kamalkoranga
> 
> My sincere appreciation goes out to you for your contribution and your efforts.
> 
> I will review your new structure and come back to you to talk about it.

Okay... I will be waiting :)

**Comment by mahmoudessam820** [comment]
Hi, @Kamalkoranga 

I reviewed your work thank you for your effort to restructure this project. 
I accept the pull request for the project and will continue working on it.

I will create GitHub Issues.
I will create branches.

1- branch development
2- branch testing
3- branch production

Please let me know what your inspiration for this project is. 
 
Please let me know how did you find my code it is easy to read and contribute?

**Comment by kamalkoranga** [comment]
> Hi, @Kamalkoranga
> 
> I reviewed your work thank you for your effort to restructure this project. I accept the pull request for the project and will continue working on it.
> 
> I will create GitHub Issues. I will create branches.
> 
> 1- branch development 2- branch testing 3- branch production
> 
> Please let me know what your inspiration for this project is.
> 
> Please let me know how did you find my code it is easy to read and contribute?

First of all Thank you for merging my code,
secondly, My inspiration for this project is that I also want to learn how can I use js framework in frontend and use flask as a backend.
At last, I find your code in flask group of linkedin and I think if we improve readme file than it would be more easy to read and contribute.

Thank you

**Comment by mahmoudessam820** [comment]
It's my pleasure to meet you and work with you.

We will be great team and will make awesome project.

I hope we can get more developers to work together.

Thanks again.

**Pull request merged**
